// Import each widget to trigger registration side effects
import "./flip-clock";
import "./life-progress";
import "./countdown";
import "./quote";
import "./pomodoro";
import "./analog-clock";
import "./focus-word";
import "./startup-tips";
import "./daily-tip";
import "./world-clock";
import "./mini-calendar";
import "./weather";
import "./moon-phase";
import "./habit-heatmap";
import "./breathing";
import "./daily-tarot";
import "./goal-ring";
import "./color-palette";
import "./water-tracker";
import "./anniversary";
import "./dday";
import "./checklist";
import "./spinner";
import "./week-planner";
import "./sticky-note";
import "./mood-tracker";
import "./book-tracker";
import "./now-playing";
import "./link-card";
import "./streak";
import "./week-progress";
import "./progress-bar";
import "./photo";
import "./date-card";
import "./typing-test";
import "./word-clock";
import "./savings-goal";

// Re-export color mode context
export { ColorModeContext, useWidgetColorMode } from "./color-mode-context";

// Re-export for direct use
export { FlipCard, FlipClockWidget } from "./flip-clock";
export { ProgressBar, LifeProgressWidget } from "./life-progress";
export { CountdownWidget } from "./countdown";
export { QuoteWidget } from "./quote";
export { PomodoroWidget } from "./pomodoro";
export { AnalogClockWidget } from "./analog-clock";
export { FocusWordWidget } from "./focus-word";
export { StartupTipsWidget } from "./startup-tips";
export { DailyTipWidget } from "./daily-tip";
export { WorldClockWidget } from "./world-clock";
export { MiniCalendarWidget } from "./mini-calendar";
export { WeatherWidget } from "./weather";
export { MoonPhaseWidget } from "./moon-phase";
export { HabitHeatmapWidget } from "./habit-heatmap";
export { BreathingWidget } from "./breathing";
export { DailyTarotWidget } from "./daily-tarot";
export { GoalRingWidget } from "./goal-ring";
export { ColorPaletteWidget } from "./color-palette";
export { WaterTrackerWidget } from "./water-tracker";
export { AnniversaryWidget } from "./anniversary";
export { DdayWidget } from "./dday";
export { ChecklistWidget } from "./checklist";
export { SpinnerWidget } from "./spinner";
export { WeekPlannerWidget } from "./week-planner";
export { StickyNoteWidget } from "./sticky-note";
export { MoodTrackerWidget } from "./mood-tracker";
export { BookTrackerWidget } from "./book-tracker";
export { NowPlayingWidget } from "./now-playing";
export { LinkCardWidget } from "./link-card";
export { StreakWidget } from "./streak";
export { WeekProgressWidget } from "./week-progress";
export { ProgressBarWidget } from "./progress-bar";
export { PhotoWidget } from "./photo";
export { DateCardWidget } from "./date-card";
export { TypingTestWidget } from "./typing-test";
export { WordClockWidget } from "./word-clock";
export { SavingsGoalWidget } from "./savings-goal";
