export interface FocusWord {
  en: string;
  ko: string;
}

export const focusWords: FocusWord[] = [
  { en: "Focus", ko: "집중" },
  { en: "Growth", ko: "성장" },
  { en: "Courage", ko: "용기" },
  { en: "Balance", ko: "균형" },
  { en: "Create", ko: "창조" },
  { en: "Persist", ko: "끈기" },
  { en: "Breathe", ko: "호흡" },
  { en: "Simplify", ko: "단순함" },
  { en: "Believe", ko: "믿음" },
  { en: "Explore", ko: "탐험" },
  { en: "Gratitude", ko: "감사" },
  { en: "Kindness", ko: "친절" },
  { en: "Patience", ko: "인내" },
  { en: "Resilience", ko: "회복력" },
  { en: "Intention", ko: "의도" },
  { en: "Clarity", ko: "명확함" },
  { en: "Momentum", ko: "추진력" },
  { en: "Purpose", ko: "목적" },
  { en: "Discipline", ko: "규율" },
  { en: "Empathy", ko: "공감" },
  { en: "Harmony", ko: "조화" },
  { en: "Innovate", ko: "혁신" },
  { en: "Learn", ko: "배움" },
  { en: "Mindful", ko: "마음챙김" },
  { en: "Optimize", ko: "최적화" },
  { en: "Progress", ko: "전진" },
  { en: "Reflect", ko: "성찰" },
  { en: "Strength", ko: "힘" },
  { en: "Trust", ko: "신뢰" },
  { en: "Unity", ko: "단결" },
  { en: "Vision", ko: "비전" },
  { en: "Wisdom", ko: "지혜" },
  { en: "Adapt", ko: "적응" },
  { en: "Begin", ko: "시작" },
  { en: "Calm", ko: "평온" },
  { en: "Dare", ko: "도전" },
  { en: "Energy", ko: "에너지" },
  { en: "Flow", ko: "흐름" },
  { en: "Grit", ko: "끈기" },
  { en: "Hope", ko: "희망" },
  { en: "Impact", ko: "영향력" },
  { en: "Joy", ko: "기쁨" },
  { en: "Leap", ko: "도약" },
  { en: "Meaning", ko: "의미" },
  { en: "Nurture", ko: "양육" },
  { en: "Overcome", ko: "극복" },
  { en: "Passion", ko: "열정" },
  { en: "Quiet", ko: "고요" },
  { en: "Renew", ko: "새로움" },
  { en: "Shine", ko: "빛남" },
];
